version: '3'

volumes:
  app-database-data:
    driver: local

services:
  web:
    container_name: base-web
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./project:/var/www/app
      - ./docker/web/site.conf:/etc/nginx/conf.d/site.conf

  app:
    container_name: base-app
    build: docker/app/.
    volumes:
      - ./project:/var/www/app

  database:
    container_name: base-database
    image: postgres:10.3
    volumes:
      - app-database-data:/var/lib/postgresql/data
      - ./docker/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=baselaravel
      - POSTGRES_MULTIPLE_DATABASES=app_dev,app_test
