version: '3'

volumes:
  app-database-data:
    driver: local

services:
  database:
    image: postgres:10.3
    volumes:
      - app-database-data:/var/lib/postgresql/data
      - ./docker/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=baselaravel
      - POSTGRES_MULTIPLE_DATABASES=app_dev,app_test
